metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false
- module: apache
  metricsets:
    - status
  enabled: true
  period: 1s
  hosts: ["http://127.0.0.1"]
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
#setup.kibana.host: "kibana:5601"
#setup.dashboards.enabled: true
