filebeat.prospectors:
- type: log
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["log"]
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  pipeline: docker_logs_pipeline
setup.kibana.host: "kibana:5601"
setup.dashboards.enabled: true
